version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: app/docker/api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: