version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: app/docker/api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: app/docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/frontend/node_modules
    depends_on:
      - api

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: app/docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/app/backend/static
    depends_on:
      - api
      - frontend
volumes:
  pgdata:
  node_modules:
  static: